module Ferrum
  class Contexts
    ALLOWED_TARGET_TYPES: ::Array[String]
    RECURSIVE_AUTO_ATTACH_TYPES: ::Array[String]

    include Enumerable[[String, Context]]

    attr_reader contexts: ::Concurrent::Map[String, Context]

    @contexts: ::Concurrent::Map[String, Context]
    @client: Client
    @default_context: Context?
    @manually_attached: ::Concurrent::Map[String, bool]

    def initialize: (Client client) -> void

    def manually_attached: (String target_id) -> true

    def default_context: () -> Context

    def each: () { ([String, Context]) -> void } -> void
            | () -> Enumerator[[String, Context], void]

    def []: (String id) -> Context?

    def find_by: (target_id: String) -> Context?

    def create: (**untyped options) -> Context

    def dispose: (String context_id) -> bool?

    def close_connections: () -> void

    def reset: () -> void

    def size: () -> ::Integer

    private

    def subscribe: () -> void

    def subscribe_attached_target: ((Client | SessionClient) client) -> void

    def subscribe_target_created: () -> void

    def rearm_auto_attach: (String session_id, String type) -> void

    def handle_attach: (Target? target, String session_id, Hash[String, untyped] params) -> void

    def detach_untracked: (String session_id) -> void

    def detach_unless_manually_attached: (Target target, String session_id) -> void

    def connect_worker: (Target target) -> void

    def resume: (String session_id) -> void

    def detach: (String session_id) -> void

    def discover: () -> void

    def auto_attach: () -> void

    def add_context: (String? context_id) -> Context?

    def find_implicit_context: () -> Context?
  end
end
