module Ferrum
  module Utils
    module Platform
      def self?.platform_name: () -> (:mac | :windows | :linux)

      def self?.windows?: () -> Integer?

      def self?.mac?: () -> Integer?

      def self?.mac_arm?: () -> Integer?

      def self?.mri?: () -> bool
    end
  end
end
