module Ferrum
  class Page
    module Stream
      STREAM_CHUNK: untyped

      def stream_to: (path: untyped, encoding: untyped, handle: untyped) -> untyped

      def stream_to_file: (path: untyped, handle: untyped) -> true

      def stream_to_memory: (encoding: untyped, handle: untyped) -> untyped

      def stream: (output: untyped, handle: untyped) -> untyped
    end
  end
end
