module Ferrum
  class Page
    class Tracing
      EXCLUDED_CATEGORIES: ::Array["*"]

      SCREENSHOT_CATEGORIES: ::Array["disabled-by-default-devtools.screenshot"]

      INCLUDED_CATEGORIES: ::Array["devtools.timeline" | "v8.execute" | "disabled-by-default-devtools.timeline" | "disabled-by-default-devtools.timeline.frame" | "toplevel" | "blink.console" | "blink.user_timing" | "latencyInfo" | "disabled-by-default-devtools.timeline.stack" | "disabled-by-default-v8.cpu_profiler" | "disabled-by-default-v8.cpu_profiler.hires"]

      DEFAULT_TRACE_CONFIG: { includedCategories: untyped, excludedCategories: untyped }

      def initialize: (untyped page) -> void

      def record: (?path: untyped?, ?encoding: ::Symbol, ?timeout: untyped?, ?trace_config: untyped?, ?screenshots: bool) { () -> untyped } -> untyped

      private

      def start: (untyped config) -> untyped

      def stop: () -> untyped

      def subscribe_tracing_complete: () -> (nil | untyped)

      def stream_handle: (untyped handle) -> untyped
    end
  end
end
